export const KEYWORDS: string[] = [
  // Name & Identity
  "Himanshu Jain",
  "Himanshu",
  "Himanshu Jain Portfolio",
  "Portfolio of Himanshu Jain",
  "Himanshu Jain Developer",
  "Himanshu Jain Website",
  "Himanshu Jain Full Stack Developer",
  "Himanshu Jain Frontend Developer",
  "Himanshu Jain Software Engineer",
  "Hire Himanshu Jain",
  "Himanshu Jain Resume",
  "himanshu works",
  "himanshu.works",
  "himanshu works portfolio",
  "portfolio himanshu.works",
  "himanshu works developer",

  // Roles & Titles
  "Software Engineer",
  "Frontend Developer",
  "Full Stack Developer",
  "React Developer",
  "Next.js Developer",
  "Freelance Developer",
  "TypeScript Developer",
  "Remote Frontend Developer",
  "Web Developer India",
  "Web Developer Portfolio",

  // Technologies
  "Next.js",
  "React",
  "TypeScript",
  "Tailwind CSS",
  "React Native",
  "JavaScript",
  "Node.js",
  "Prisma",
  "MongoDB",
  "Express.js",
  "Solana Developer",
  "Web3 Developer",
  "Blockchain Developer",
  "Ethereum",
  "Vercel",

  // Niche & Tools
  "Frontend Portfolio",
  "Developer Portfolio",
  "Tech Portfolio",
  "Open Source Developer",
  "Clean UI Developer",
  "Performance Web Dev",
  "Modern Web Development",
  "Web Animation Portfolio",
  "SEO Optimized Portfolio",

  // Location & Branding
  "Indian Developer",
  "Developer from India",
  "Software Engineer India",
  "Remote Developer India",
  "Frontend Engineer India",
  "Full Stack Developer India",

  // Intent Based
  "Hire frontend developer",
  "Hire full stack developer",
  "Download developer resume",
  "Freelance Next.js Developer",
  "Personal website of Himanshu Jain",
];
